# Generated by Django 3.1.6 on 2021-02-18 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ingredient_Name', models.CharField(max_length=50)),
                ('Inventory_Quantity', models.FloatField()),
                ('Ingredient_Price', models.FloatField()),
                ('Ingredient_PricePerGram', models.FloatField()),
                ('Restaurant_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.restaurantregistrationtable')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=100)),
                ('Item_Category', models.CharField(choices=[('fooditem', 'Food Item'), ('beverage', 'Beverage')], max_length=20)),
                ('Item_Type', models.CharField(choices=[('veg', 'Veg'), ('nonveg', 'Non-Veg')], max_length=10)),
                ('Cost_Price', models.FloatField()),
                ('Item_GST', models.IntegerField()),
                ('Item_ProfitMargin', models.IntegerField()),
                ('Selling_Price', models.FloatField()),
                ('Restaurant_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.restaurantregistrationtable')),
            ],
        ),
        migrations.CreateModel(
            name='SeatManagementTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Table_Number', models.IntegerField()),
                ('Number_Of_Covers', models.IntegerField()),
                ('Restaurant_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.restaurantregistrationtable')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeRequirementsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ingredient_Name', models.CharField(max_length=50)),
                ('Ingredient_Quantity', models.FloatField()),
                ('Ingredient_PricePerGram', models.FloatField()),
                ('Total_Ingredient_Price', models.FloatField()),
                ('Ingredient_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RMS.inventorytable')),
                ('Item_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RMS.menuitemstable')),
                ('Restaurant_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.restaurantregistrationtable')),
            ],
        ),
    ]
