# Generated by Django 3.1.6 on 2021-02-27 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorytable',
            old_name='Restaurant_ID',
            new_name='Restaurant',
        ),
        migrations.RenameField(
            model_name='menuitemstable',
            old_name='Restaurant_ID',
            new_name='Restaurant',
        ),
        migrations.RenameField(
            model_name='reciperequirementstable',
            old_name='Ingredient_ID',
            new_name='Ingredient',
        ),
        migrations.RenameField(
            model_name='reciperequirementstable',
            old_name='Item_ID',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='reciperequirementstable',
            old_name='Restaurant_ID',
            new_name='Restaurant',
        ),
        migrations.RenameField(
            model_name='seatmanagementtable',
            old_name='Restaurant_ID',
            new_name='Restaurant',
        ),
    ]
