# Generated by Django 3.1.6 on 2021-03-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0002_auto_20210228_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemstable',
            name='Recipe',
            field=models.BooleanField(default=False),
        ),
    ]
