# Generated by Django 3.1.6 on 2021-04-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0003_menuitemstable_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemstable',
            name='Item_Category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='menuitemstable',
            name='Item_Type',
            field=models.CharField(max_length=10),
        ),
    ]
