# Generated by Django 3.1.6 on 2021-04-05 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermanagementtable',
            old_name='Restaurant_ID',
            new_name='Restaurant',
        ),
    ]
