# Generated by Django 3.1.6 on 2021-04-05 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0003_auto_20210405_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitemstable',
            old_name='Customer_ID',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='orderitemstable',
            old_name='Item_ID',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='orderitemstable',
            old_name='Restaurant_ID',
            new_name='Restaurant',
        ),
    ]
