# Generated by Django 3.1.6 on 2021-04-07 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0004_auto_20210406_0213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermanagementtable',
            old_name='Customer_ID',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='ordermanagementtable',
            old_name='Restaurant_ID',
            new_name='Restaurant',
        ),
    ]
