# Generated by Django 3.1.6 on 2021-04-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0005_auto_20210408_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermanagementtable',
            name='Invoice',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
