# Generated by Django 3.1.6 on 2021-04-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0006_auto_20210408_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermanagementtable',
            name='Number_of_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordermanagementtable',
            name='Table_Number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
