# Generated by Django 3.1.6 on 2021-04-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0007_auto_20210408_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermanagementtable',
            name='Order_Completed',
            field=models.BooleanField(default=False),
        ),
    ]
