# Generated by Django 3.1.6 on 2021-02-27 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_auto_20210228_0456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerregistrationtable',
            old_name='Restaurant_ID',
            new_name='Restaurant',
        ),
        migrations.RenameField(
            model_name='staffregistrationtable',
            old_name='Restaurant_ID',
            new_name='Restaurant',
        ),
    ]
